version: 1
replicaCount: 3

application:
  cluster: searchmania

infrastructure:
  namespace: searchzone
  appName: elasticsearch

service:
  type: LoadBalancer
  httpPort: 9200
  clusterPort: 9300
  protocol: TCP