apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: {{ .Values.infrastructure.namespace }}
  labels:
      cluster: {{ .Values.application.cluster }}
spec:
  version: 8.1.1
  nodeSets:
  - name: {{ .Values.application.cluster }}
    count: {{ .Values.replicaCount }}
    config:
      node.store.allow_mmap: false