apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: quickstart
  namespace: {{ .Values.infrastructure.namespace }}
  labels:
      cluster: {{ .Values.application.cluster }}
spec:
  version: 8.1.1
  nodeSets:
  - name: {{ .Values.application.cluster }}
    count: {{ .Values.replicaCount }}
    config:
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          elastic: quickstart
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 4Gi
              cpu: 1
            requests:
              memory: 4Gi
              cpu: 1
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms2g -Xmx2g"
      volumeClaimTemplates:
      - metadata:
         name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 8Gi
          storageClassName: managed-premium
